### ISSUE TITLE
Misc. PlantUML problems

### ISSUE THREAD

**Issue by ascheman** [kontext-e/jqassistant-plugins#44]
The PlantUML scanner has some problems, it is not able to handle the following cases:
- PlantUML is robust, e.g., you may drop the `{}` if it is empty
- Create packages with `as` notation for shortcuts
- use `note ... note end`

If you use them, for instance from the kontext-e/uneven-problems project just
- drop `{}` from one of the packages
- provide a short cut `as` to one of the packages
- add a note

the scanner will throw Exceptions (NPEs or other).

**Comment by kontext-e** [comment]
Since I'm using the plantuml.jar now for scanning the diagrams, these problems should be gone. Using the short cut `as` and a note worked, as well as many other things that did not before.
But dropping the empty `{}` does not work with any of my PlantUML instances: the IntelliJ preview plugin or the plantuml.jar itself. No exception is thrown, but the diagram is not inserted into the database. PlantUML reports an
> Error while parsing at postion 5:
